"""Delete profile

Revision ID: b3f49fbb6cfa
Revises: 74a7ac4ec8c9
Create Date: 2024-11-30 12:10:04.515194

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b3f49fbb6cfa"
down_revision: Union[str, None] = "74a7ac4ec8c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("profile")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profile",
        sa.Column(
            "first_name",
            sa.VARCHAR(length=40),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "last_name",
            sa.VARCHAR(length=40),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "user_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "username",
            sa.VARCHAR(length=32),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="profile_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="profile_pkey"),
        sa.UniqueConstraint("email", name="profile_email_key"),
        sa.UniqueConstraint("user_id", name="profile_user_id_key"),
        sa.UniqueConstraint("username", name="profile_username_key"),
    )
    # ### end Alembic commands ###
