"""password edit type 2

Revision ID: 74a7ac4ec8c9
Revises: 782ca79fc8a4
Create Date: 2024-11-24 01:16:54.204352

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "74a7ac4ec8c9"
down_revision: Union[str, None] = "782ca79fc8a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "password",
        existing_type=sa.VARCHAR(),
        type_=sa.LargeBinary(),
        existing_nullable=False,
        postgresql_using="password::bytea",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "password",
        existing_type=sa.LargeBinary(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
