"""New revision

Revision ID: fe4e94978c4d
Revises: d6effc37f216
Create Date: 2024-11-23 19:54:29.377520

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fe4e94978c4d"
down_revision: Union[str, None] = "d6effc37f216"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profile", sa.Column("username", sa.String(length=32), nullable=False)
    )
    op.add_column("profile", sa.Column("email", sa.String(), nullable=False))
    op.create_unique_constraint(None, "profile", ["username"])
    op.create_unique_constraint(None, "profile", ["email"])
    op.add_column("user", sa.Column("email", sa.String(), nullable=False))
    op.add_column(
        "user", sa.Column("password", sa.LargeBinary(), nullable=False)
    )
    op.drop_constraint("user_username_key", "user", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("user_username_key", "user", ["username"])
    op.drop_column("user", "password")
    op.drop_column("user", "email")
    op.drop_constraint(None, "profile", type_="unique")
    op.drop_constraint(None, "profile", type_="unique")
    op.drop_column("profile", "email")
    op.drop_column("profile", "username")
    # ### end Alembic commands ###
