"""user edit username field

Revision ID: e21943342b2f
Revises: 4eb6b70540c4
Create Date: 2024-11-24 00:54:32.846631

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e21943342b2f"
down_revision: Union[str, None] = "4eb6b70540c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "username", existing_type=sa.VARCHAR(length=32), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "username", existing_type=sa.VARCHAR(length=32), nullable=False
    )
    # ### end Alembic commands ###
