"""Database creation

Revision ID: 3541306ba801
Revises: 12b2a70f5fd5
Create Date: 2024-12-14 19:12:30.433980

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3541306ba801"
down_revision: Union[str, None] = "12b2a70f5fd5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("order", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "order", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "order", type_="foreignkey")
    op.drop_column("order", "user_id")
    # ### end Alembic commands ###
