"""Creation order_product2

Revision ID: b7c4811b2764
Revises: af9565b0b3d8
Create Date: 2024-12-11 22:07:55.928091

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b7c4811b2764"
down_revision: Union[str, None] = "af9565b0b3d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "order_product_association",
        "order_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "order_product_association",
        "product_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.drop_constraint(
        "order_product_association_order_id_product_id_key",
        "order_product_association",
        type_="unique",
    )
    op.create_unique_constraint(
        "id_unique_order_product",
        "order_product_association",
        ["order_id", "product_id"],
    )
    op.create_unique_constraint(
        None, "order_product_association", ["order_id"]
    )
    op.create_unique_constraint(
        None, "order_product_association", ["product_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "order_product_association", type_="unique")
    op.drop_constraint(None, "order_product_association", type_="unique")
    op.drop_constraint(
        "id_unique_order_product", "order_product_association", type_="unique"
    )
    op.create_unique_constraint(
        "order_product_association_order_id_product_id_key",
        "order_product_association",
        ["order_id", "product_id"],
    )
    op.alter_column(
        "order_product_association",
        "product_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "order_product_association",
        "order_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    # ### end Alembic commands ###
