"""Database add count in order_product

Revision ID: ffdd5131ffe2
Revises: b7c4811b2764
Create Date: 2024-12-13 20:53:25.264622

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ffdd5131ffe2"
down_revision: Union[str, None] = "b7c4811b2764"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_product_association",
        sa.Column("count", sa.Integer(), server_default="1", nullable=False),
    )
    op.drop_constraint(
        "id_unique_order_product", "order_product_association", type_="unique"
    )
    op.drop_constraint(
        "order_product_association_order_id_key",
        "order_product_association",
        type_="unique",
    )
    op.drop_constraint(
        "order_product_association_product_id_key",
        "order_product_association",
        type_="unique",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "order_product_association_product_id_key",
        "order_product_association",
        ["product_id"],
    )
    op.create_unique_constraint(
        "order_product_association_order_id_key",
        "order_product_association",
        ["order_id"],
    )
    op.create_unique_constraint(
        "id_unique_order_product",
        "order_product_association",
        ["order_id", "product_id"],
    )
    op.drop_column("order_product_association", "count")
    # ### end Alembic commands ###
