"""Database creation

Revision ID: 085b4a99c7fe
Revises: c50704230652
Create Date: 2024-12-14 19:46:09.483560

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "085b4a99c7fe"
down_revision: Union[str, None] = "c50704230652"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order",
        sa.Column(
            "order_status",
            sa.String(),
            server_default="ACTIVE",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order", "order_status")
    # ### end Alembic commands ###
